title: <p align="center"> Shiva sai Bondugula </p>
logo: /assets/img/shiva.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/bondugula-shiva-sai">LinkedIn</a> |
  <a href="https://github.com/shivasaibondugula">GitHub</a>
  
  <br>   
  Software engineer at Infor
  <br>
  </p>
  
theme: jekyll-theme-minimal
